version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "30000:80"
  helloworld:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "30001:80"
  helloworldnode:
    environment:
      - NODE_ENVIRONMENT=Development
      - PORT=80
    ports:
      - "30002:80"